openapi: 3.0.0
info: 
  title: E-commerce API
  description: Creation of API for e-commerce store
  version: 1.0.0
  contact: 
    email: paraspatil248@gmail.com

servers: 
  - url: "{protocol}://localhost:4000/api/{version}"
    description: for localhost
    variables: 
      version:
        enum: 
          - v1

        default: v1
      protocol:
        enum:
          - http
          - https
        default: http

components: 
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token
    BearerAuth:
      type: http
      scheme: bearer

paths: 
  /dummy:
    get:
      tags:
        - Home page
      summary: returns a greet from servers
      responses: 
        200:
          description: All good success
        400: 
          description: Bad request
        500: 
          description: internal server error